apiVersion: apps/v1
kind: Deployment
metadata:
  name: heartbeat-probe
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: heartbeat-probe
  template:
    metadata:
      labels:
        app: heartbeat-probe
    spec:
      nodeSelector:
        location: china
      containers:
        - name: probe
          image: ghcr.mirror.nbtca.space/nbtca/heartbeat-probe:latest
          imagePullPolicy: Always
          env:
            - name: PROBE_TOKEN
              valueFrom:
                secretKeyRef:
                  name: heartbeat-probe
                  key: token
          resources:
            requests:
              memory: "32Mi"
              cpu: "10m"
            limits:
              memory: "128Mi"
              cpu: "200m"
